name: VALIDATE

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 * * SUN'

jobs:
  build:
    strategy:
      matrix:
        BUILD_TYPE: [Release, Debug]
        DISTRO: ['fedora']
        CXX: ['g++', 'clang++']
        EXTERNAL_MPI4PY: ['On']
        include:
          - BUILD_TYPE: 'Debug'
            DISTRO: 'fedora_intel'
            CXX: 'icpc'
            EXTERNAL_MPI4PY: 'On'
          - BUILD_TYPE: 'Debug'
            DISTRO: 'fedora_intel-oneapi'
            CXX: 'icpx'
            EXTERNAL_MPI4PY: 'On'

    runs-on: ubuntu-latest
    container: espressopp/buildenv:${{ matrix.distro }}
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: ${{ matrix.DISTRO }}-${{ matrix.CXX }}-${{ matrix.BUILD_TYPE }}-${{ github.run_id }}
          restore-keys: ${{ matrix.DISTRO }}-${{ matrix.CXX }}-${{ matrix.BUILD_TYPE }}

      - uses: actions/checkout@v2

      - name: Get trail license
        if: ${{ matrix.CXX == 'icpc' }}
        run: |
          mkdir ~/Licenses
          curl https://dynamicinstaller.intel.com/api/v2/license > ~/Licenses/intel.lic
      
      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE }} -DCMAKE_CXX_COMPILER=${{ matrix.CXX }} -DEXTERNAL_MPI4PY=${{ matrix.EXTERNAL_MPI4PY }}

      - name: Build
        run: cmake --build build --verbose --target all -j 2

      - name: Install
        run: cmake --install build

      - name: Test
        working-directory: build
        run: ctest --rerun-failed --output-on-failure -j 2

  documentation:
    runs-on: ubuntu-latest
    environment: CI
    container: espressopp/buildenv:fedora
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'espressopp'

      - name: build documentation
        run: |
          cmake -S espressopp -B espressopp-build
          cmake --build espressopp-build --target doxygen sphinx sphinx-pdf -j 2

      - uses: actions/checkout@v2
        with:
          repository: 'espressopp/espressopp.github.io.git'
          ref: 'master'
          path: 'html'

      - name: update docu repo
        working-directory: ${{github.workspace}}/html
        run: |
          rm -rf *
          mv ../espressopp-build/doc/sphinx/html/* .
          mv ../espressopp-build/doc/sphinx/pdf/ESPResSo++.pdf .

      - name: commit
        working-directory: ${{github.workspace}}/html
        run: |
          git config --global user.name "Automatic Deployment (GitHub Action)";
          git config --global user.email "espp-devel@listserv.mpip-mainz.mpg.de";
          git add --all && git commit -m "Documentation Update";

      - name: register deploy key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.PAGES_KEY }}"
        if: github.ref == 'refs/heads/master'

      - name: deploy documentation
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        working-directory: ${{github.workspace}}/html
        run: git push git@github.com:espressopp/espressopp.github.io.git master;
        if: github.ref == 'refs/heads/master'

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: espressopp

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: github.ref == 'refs/heads/master'

      - name: Build and Push Docker Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ${{github.workspace}}
          file: espressopp/.github/workflows/Dockerfile
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: espressopp/espressopp:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

